# Makefile for debugging example
# Mark Ardis, RIT, 10/27/2006


prime:	prime.c
	gcc -g -Wall -o prime prime.c
prime_standard: prime_standard.c
	gcc -g -Wall -o prime_standard prime_standard.c
clean:
	rm -f prime  prime_standard

